[package]
name = "data-collector"
version = "0.4.0"
authors = ["Timo Kr√∂ger <timokroeger93@gmail.com>"]
description = "Configurable Modbus client which sends the collected data to InfluxDB"
edition = "2018"
publish = false

[dependencies]
clap = "2"
humantime = "1.2"
log = "0.4"
modbus = { git = "https://github.com/TimoKroeger/modbus-rs", branch = "slave_id" }
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde-humantime = "0.1"
simplelog = "0.5"
toml = "0.5"
